### ISSUE TITLE
[YouTube]South Park: The Stick of Truth

### ISSUE THREAD

**Issue by PrzemoGaluszka** [pgaluszka/pgaluszka.github.io#23]
https://www.youtube.com/playlist?list=PLSNHYokPbz2Tp07JRp5d3tbKMonHTi4Rp

**Comment by PrzemoGaluszka** [comment]
Odcinek 19 został dodany na YT -  ostatni odcinek serii.
Zamykam #23.
CC: @pgaluszka

**Comment by PrzemoGaluszka** [comment]
Trzeba stworzyć wpis na blogu przed zamknięciem.

**Comment by PrzemoGaluszka** [comment]
Zamykam #23. 
cc: @pgaluszka

**Comment by pgaluszka** [comment]
Accepted Closed.
